import { eq, sql } from "drizzle-orm";
import { db, isDbConnected } from "../../db";
import { users, markets, positions } from "@nexus/db";
import { mockMarkets, mockPositions } from "../../mockStore";
import { jsonRes } from "../../utils/response";

export async function handlePostAiPortfolioAnalyze(req: Request, session: any) {
  let totalBalanceUsd = 10000000;
  let userPosList: any[] = [];
  let userMarkets: any[] = [];

  if (!isDbConnected) {
    userPosList = mockPositions.filter(p => p.userId === session.id);
    userMarkets = mockMarkets;
  } else {
    const userRows = await db.select().from(users).where(eq(users.id, session.id));
    if (userRows.length > 0) totalBalanceUsd = userRows[0].balanceUsd;
    userPosList = await db.select().from(positions).where(eq(positions.userId, session.id));
    const marketIds = [...new Set(userPosList.map(p => p.marketId))];
    if (marketIds.length > 0) {
      userMarkets = await db.select().from(markets).where(sql`${markets.id} IN ${marketIds}`);
    }
  }

  let totalPortfolioValue = 0, totalCostBasis = 0;
  const categoryMap: Record<string, number> = {};

  const positionsWithDetails = userPosList.map(pos => {
    const m = userMarkets.find(x => x.id === pos.marketId);
    const currentPrice = m ? (pos.outcome === "YES" ? m.yesPrice : m.noPrice) : 50;
    const value = pos.quantity * currentPrice;
    totalPortfolioValue += value;
    totalCostBasis += pos.quantity * pos.averageBuyPrice;
    const category = m ? m.category : "Unknown";
    categoryMap[category] = (categoryMap[category] || 0) + value;

    return { question: m ? m.question : pos.marketId, category, outcome: pos.outcome, quantity: pos.quantity, averageBuyPrice: pos.averageBuyPrice, currentPrice, currentValueUsd: value / 100, pnlUsd: (value - (pos.quantity * pos.averageBuyPrice)) / 100 };
  });

  const allocations: Record<string, number> = {};
  if (totalPortfolioValue > 0) {
    for (const [cat, val] of Object.entries(categoryMap)) allocations[cat] = Math.round((val / totalPortfolioValue) * 100);
  } else {
    allocations["Crypto"] = 0; allocations["Sports"] = 0; allocations["Politics"] = 0;
  }

  const pnlUsd = (totalPortfolioValue - totalCostBasis) / 100;
  const totalNetWorthUsd = (totalBalanceUsd + totalPortfolioValue) / 100;
  const GEMINI_API_KEY = process.env.GEMINI_API_KEY || "";

  if (!GEMINI_API_KEY) {
    const cryptoAlloc = allocations["Crypto"] || 0;
    const riskLevel = totalPortfolioValue > 0 && cryptoAlloc > 50 ? "HIGH" : "MEDIUM";
    const recommendation = totalPortfolioValue === 0 
      ? "Your portfolio is empty. Fund your account and scale into diversified Sports or Politics markets."
      : cryptoAlloc > 50 ? "Diversify into Sports markets." : "Your portfolio is well-balanced.";

    const mockReport = `### 🧠 AI Portfolio Advisor Audit\n\n**Portfolio Risk Level**: ${riskLevel === "HIGH" ? "🔴 **HIGH**" : "🟡 **MEDIUM**"}\n\n#### 📊 Allocation Analysis\n${Object.entries(allocations).map(([cat, pct]) => `- **${cat}**: ${pct}%`).join("\n") || "- No active holdings."}\n\n#### 📈 Performance Summary\n- **Cash Balance**: $${(totalBalanceUsd / 100).toFixed(2)} USD\n- **Portfolio Value**: $${(totalPortfolioValue / 100).toFixed(2)} USD\n- **Total Net Worth**: $${totalNetWorthUsd.toFixed(2)} USD\n- **Unrealized PnL**: ${pnlUsd >= 0 ? "+" : ""}$${pnlUsd.toFixed(2)} USD\n\n#### 🔍 Risk Exposure & Recommendations\n1. **Concentration**: ${totalPortfolioValue === 0 ? "No active market exposure." : `Concentration of ${Math.max(...Object.values(allocations))}% in largest category.`}\n2. **Actionable Diversification**: ${recommendation}\n\n*Disclaimer: This audit is generated by an AI Agent and is Not Financial Advice (NFA).*`;

    return jsonRes({ riskLevel, allocations, pnlUsd, recommendation, report: mockReport });
  }

  try {
    const systemInstructions = `You are the PredictX Portfolio Advisor Agent. Analyze the user's prediction market portfolio and provide a professional risk audit in JSON format: { "riskLevel": "LOW" | "MEDIUM" | "HIGH", "allocations": { "Crypto": number, "Sports": number, "Politics": number }, "pnlUsd": number, "recommendation": "string", "report": "markdown_string" }`;
    const prompt = `User cash balance: $${(totalBalanceUsd / 100).toFixed(2)} USD\nActive positions:\n${JSON.stringify(positionsWithDetails, null, 2)}\nCalculated allocations:\n${JSON.stringify(allocations, null, 2)}\nTotal Unrealized PnL: $${pnlUsd.toFixed(2)} USD\nTotal Net Worth: $${totalNetWorthUsd.toFixed(2)} USD`;

    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_API_KEY}`;
    const response = await fetch(url, {
      method: "POST", headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ contents: [{ parts: [{ text: `${systemInstructions}\n\n${prompt}` }] }], generationConfig: { responseMimeType: "application/json" } })
    });

    if (!response.ok) throw new Error("Gemini Portfolio API error");
    const data = await response.json() as any;
    const rawText = data.candidates[0].content.parts[0].text;
    return jsonRes(JSON.parse(rawText.trim()));
  } catch (err) {
    console.error("Gemini portfolio audit failed, using fallback:", err);
    return jsonRes({ riskLevel: "MEDIUM", allocations, pnlUsd, recommendation: "Seek sector diversification.", report: "Failed to generate AI report." });
  }
}
